### ISSUE TITLE
自定义节点 如何设置锚点？

### ISSUE THREAD

**Issue by evanoxu** [DiceGraph/g6-react-node#1]
如题。
在自定义节点的时候，我该如何设置锚点 覆盖 默认的getAnchorPoints设置？

**Comment by evanoxu** [comment]
尝试了在注册的时候，解构赋值。
（虽然一直报错提醒，但是能编译通过。如图）
![20210520113459](https://user-images.githubusercontent.com/3927965/118915407-791e6980-b95f-11eb-9321-13d19a04a32e.jpg)

到底 自定义节点 设置自定义锚点 的正确方法是什么？

**Comment by mxz96102** [comment]
这周1.4.0应该已经修复了类型问题，因为当初写类型的时候有些问题，请更新一下@antv/g6-react-node@1.4.0再看看

**Comment by evanoxu** [comment]
可以了。
